export const CHAT_MESSAGE_INPUT = 'CHAT_MESSAGE_INPUT';
export const ALL_CHAT_MESSAGES = 'ALL_CHAT_MESSAGES';

export const LOAD_CHAT_SUCCESS = 'LOAD_CHAT_SUCCESS';
export const LOAD_CHAT_FAILURE = 'LOAD_CHAT_FAILURE';
